## SVD

Where A is the real m x n matrix that we wish to decompose, U is an m x m matrix, Sigma (often represented by the uppercase Greek letter Sigma) is an m x n diagonal matrix, and V^T is the  transpose of an n x n matrix where T is a superscript.

In [1]:
# EXPERIMENT WITH THE SVD FUNCTION
import numpy as np
import math

In [2]:
# Singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# SVD
U, s, VT = svd(A)
print(U)
print(s)
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [ ]:
A = array([[2, 2], [-1, 1]])

Z = array([[0, 0], [0, 2]])

z_hat = A+Z

np.transpose(A)

a = np.matmul(np.transpose(A), A)

np.linalg.eig(a)

1/math.sqrt(2) # normalized the eigenvectors

v_1 = array([1/math.sqrt(2), 1/math.sqrt(2)])

v_1.shape

v_2 = array([-1/math.sqrt(2), 1/math.sqrt(2)])



# FOR EIGENS, NEED TO MATMUL THE MATRIX FIRST
a = np.matmul(np.transpose(A), A)
np.linalg.eig(a)
# np.linalg.eigvals(a)


In [69]:
A = array([[2, 2], [-1, 1]])
A

array([[ 2,  2],
       [-1,  1]])

In [195]:
I = np.identity(2)
I

array([[1., 0.],
       [0., 1.]])

In [272]:
# Z_old = np.zeros((2, 2))
Z_old

array([[ 0.        ,  0.        ],
       [ 0.        , -0.51649845]])

In [ ]:
u, d, vt = svd(A)

D = d * I
D

In [94]:
uD = np.matmul(u, D)

In [95]:
np.matmul(uD, vt)

array([[ 2.,  2.],
       [-1.,  1.]])

In [103]:
h = .5

In [104]:
thres = D - h # set all negatives to 0

## SOFT THRESHOLDING

In [322]:
# EASIER EXAMPLE TO ILLUSTRATE THE METHOD. THE MATRIX IS A 2X2 MISSING THE BOTTOM RIGHT ENTRY (SET TO ZERO FOR EASE)
X = array([[2, 2], [-1, 0]]) # (1,1) element = 0 = nan

In [340]:
def simple_svt(X, h): 
    
    '''Very basic svt for a 2x2 matrix with the (1, 1) element (only) missing'''
    
    I = np.identity(2)
     

    def svt(X, Z_old_com):
        X_hat = X + Z_old_com
        u, d, vt = svd(X_hat)
        S_D = (d * I) - h        
        S_D[S_D < 0] = 0
        uS_D = np.matmul(u, S_D)
        Z_new = np.matmul(uS_D, vt)
        return(Z_new)    
    def complement(Z):
        z_element = Z.item((1,1))
        # If not below tau, yank the approximated missing value
        # Update as the complementary matrix. All none approximated entries should be zero
        
        Z_com = np.zeros((2, 2))
        Z_com[1][1] = z_element   
        return(Z_com)            
    def norm(dframe):
        set_ = []
        for item in dframe.reshape(1, 4):
            set_.append(item**2)
        return(np.sum(set_))
    
    Z_old = np.zeros((2, 2))
    Z_old_com = complement(Z_old)
    Z_new = svt(X, Z_old_com)
      
    # prevents denominator from being = 0
    tau = norm(Z_new - Z_old)/(norm(Z_old) + 1e-7)
    print(tau)
    while tau > .001:
                
        print('nope')
        Z_old = Z_new
        Z_old_com = complement(Z_old)
        Z_new = svt(X, Z_old_com)
        
        tau = norm(Z_new - Z_old)/(norm(Z_old) + 1e-7)
        print(tau)
    X_complete = X + complement(Z_new)
    return(X_complete)
    # Start over


In [341]:
# GOOD TIMES!
simple_svt(X, .5)

58944487.2453601
nope
0.0098605516956873
nope
0.0030850033412746216
nope
0.0005320877880837324


array([[ 2.       ,  2.       ],
       [-1.       , -0.6566291]])